### ISSUE TITLE
How to rotate an image? 

### ISSUE THREAD

**Issue by logankilpatrick** [jkrumbiegel/MakieLayout#12]
Hey! 

I am doing this:         `image!(axes[i, j], img[rand(400:500):1:500, rand(400:500):1:500])`

However, the image is not correctly orientated. How can I fix this?

**Comment by logankilpatrick** [comment]
I used to rotate the sub-scene that the image was part of but I can't do that anymore I don't think.

**Comment by jkrumbiegel** [comment]
that's a classic problem with images in plotting, because julia uses column major arrays, the axis orientation of the image data doesn't match our visual expectation. there are functions that help with this, I think your best bet is `rotr90` or `rotl90`, or maybe you need to `reverse(arr, dim=(1 or 2))`

**Comment by logankilpatrick** [comment]
Awesome, Thanks. Why does makie not just do that under the hood when someone call's `image!()`?

**Comment by jkrumbiegel** [comment]
I don't know, it might be nice if the option was a keyword, you could make that an issue in AbstractPlotting. But in general AbstractPlotting can't know what kind of array your image is, so there can only be a more sensible default if it turns out all normal images are rotated when you plot them. In matplotlib or Matlab I remember there's the issue that between heatmap and image one of them is always plotted upside down... 🤷‍♂
