### ISSUE TITLE
Contour plot goes outside axis limits

### ISSUE THREAD

**Issue by grero** [jkrumbiegel/MakieLayout#15]
I came across an apparent bug in how contour plots are handled by MakieLayout. Basically, the plots do not seem to respect the axis limits. The following example should illustrate what I mean

```julia
using Makie, MakieLayout, Distributions, LinearAlgebra
#generate some data in a very clunky way
#test
P1 = MvNormal([-0.5, 0.5], 0.5*Diagonal([1.0, 1.0]))
P2 = MvNormal([0.5, -0.5], 0.5*Diagonal([1.0, 1.0]))
PP = fill(0.0, 100,100)
xx = range(-1.0, length=100, stop=1.0)
yy = range(-1.0, length=100, stop=1.0)
for j in 1:100
    for i in 1:100
        PP[i,j] += pdf(P1, [xx[j], yy[i]]) + pdf(P2, [xx[j],yy[i]])
    end
end

#plot the distributions using a contour plot, with the top panel empty
scene = Scene()
maingl = GridLayout(
           2, 1,
           parent = scene,
           colsizes = [Relative(1.0)],
           alignmode = Outside(20, 20, 20, 20))
    las = [maingl[i, j] = LayoutedAxis(scene) for i in 1:2, j in 1:1]
contour!(las[2,1], xx,yy,PP)
scene
```
![test1](https://user-images.githubusercontent.com/1245900/70964084-8594f780-20c5-11ea-842e-8f32dd8d2e72.png)

**Comment by SimonDanisch** [comment]
Just checked with @jkrumbiegel, this should work... So it's likely an old GLMakie/AbstractPlotting version, that didn't clip correctly!

**Comment by jkrumbiegel** [comment]
that looks weird :) I can't reproduce it in my current version, so maybe things got fixed along the way? Or could be an older GLMakie that's the issue (because of scene clipping), try updating that to master maybe? And soon I'll tag a new version of MakieLayout that has a lot of changes anyway

**Comment by jkrumbiegel** [comment]
nice timing

**Comment by SimonDanisch** [comment]
Master shouldn't be necessary! The clipping change should have been tagged quite a while ago!

**Comment by grero** [comment]
Hm, so I just updated all dependencies and now there is no plot, just an empty scene. Note, that this was after I changed LayoutedAxis to LAxis (thanks for shortening that! : ). Could I trouble someone to point out if there are other changes necessary to the example above to make it work? Thanks!

**Comment by jkrumbiegel** [comment]
You always need `scene = Scene(camera = campixel!)` because the axis decorations are using pixel coordinates. Otherwise they end up who knows where in screen space and are not visible. I just made a small convenience function yesterday that sets up a correct scene with the top level grid layout, so I'll probably export something like that, too, because I'm easily annoyed by having to type this boilerplate stuff again and again :)

**Comment by grero** [comment]
Hm, something must be really wrong with my setup. Now, the layouted axes appear squashed in the corner of the scene. This is what I'm doing

```julia
(MakieLayoutTests) pkg> st
    Status `~/Documents/programming/julia/MakieLayoutTests/Project.toml`
  [5789e2e9] FileIO v1.2.0
  [ee78f7c6] Makie v0.9.5
  [5a521ce4] MakieLayout v0.2.0 #master (https://github.com/jkrumbiegel/MakieLayout.jl.git)

using Makie, MakieLayout
scene = Scene(resolution = (1000,1000));
screen = display(scene) # not sure if this is needed, but I got it from one of the examples
campixel!(scene)
maingl = GridLayout(
                  2, 1,
                  parent = scene,
                  colsizes = [Relative(1.0)],
                  alignmode = Outside(20, 20, 20, 20))
las = [maingl[i, j] = LAxis(scene) for i in 1:2, j in 1:1]
scene
```
![test2](https://user-images.githubusercontent.com/1245900/71062570-cebc7880-21a5-11ea-8c11-6d069f3c8ae8.png)

**Comment by jkrumbiegel** [comment]
oh sorry, I forgot another change that needs to happen. You still have the old syntax `parent = scene` but grids don't have parents anymore, they only have suggested boundingboxes that are either connected to some boundingbox node that tells them to relayout or depend only on what they are told by other gridlayouts or their content. so either you use the scene's boundingbox like this:

`GridLayout(scene)`

Which is equivalent to:

`GridLayout(bbox = lift(x -> BBox(x), pixelarea(scene))`

Or you supply the boundingbox yourself like

`GridLayout(bbox = BBox(0, 100, 0, 100)`

If you don't supply anything, this boundingbox is the default so that's why things are squished into the lower corner.

**Comment by jkrumbiegel** [comment]
so here's your edited example:

```julia
using Makie, MakieLayout
scene = Scene(resolution = (1000,1000), camera = campixel!);
# this is only needed if you want to see the scene at this point already, I use it for debugging
# so I see what state it crashed in:
# screen = display(scene)
# otherwise the scene at the end will also show everything


# you don't need to pre-specify rows and columns if you leave them at auto size anyway,
# they get created when you put content there
maingl = GridLayout(scene, alignmode = Outside(20))

las = [LAxis(scene) for i in 1:2]
# you can assign an array of objects in one go if the index fits its shape
# even if the rows and columns don't exist yet, one object after another is placed
# and placing into a slot that doesn't exist yet creates all necessary rows an columns
# with Auto(true) size
maingl[1:2, 1] = las

scene
```

**Comment by jkrumbiegel** [comment]
I will work on updating the documentation soon, now that I've made so many changes

**Comment by grero** [comment]
Thanks! That worked like a charm : )
