### ISSUE TITLE
add a `titleposition` property to adjust the position of the title

### ISSUE THREAD

**Issue by rapus95** [jkrumbiegel/MakieLayout#17]

**Comment by jkrumbiegel** [comment]
There is a titlealign property, do you need something else?

**Comment by rapus95** [comment]
`:bottom` didn't seem to work. I want to place the title sometimes at top, sometimes at bottom and sometimes at the sides.

**Comment by jkrumbiegel** [comment]
can you post example code of what you're trying to do? are you talking about a single axis' title?

**Comment by rapus95** [comment]
![image](https://user-images.githubusercontent.com/5960902/71009105-00700980-20ea-11ea-80ea-05bfc71a3b00.png)
Something like that, where the title of the upper plot is on its upper side and the one of the lower plot is on its lower side.

**Comment by jkrumbiegel** [comment]
I might implement that at some point, not sure how common that use case is, especially because you can use the xlabel for the same purpose. But you always have the option to place a LText in the protrusion under the axis. Example:

```julia
using Makie
using MakieLayout

begin
    scene = Scene(camera = campixel!)

    g = GridLayout(scene, alignmode = Outside(30))
    g[1, 1] = LAxis(scene)
    ax = g[2, 1] = LAxis(scene)
    hidexdecorations!(ax)
    g[2, 1, Bottom()] = LText(scene, "Bottom title",
        textsize = 30, padding = (0, 0, 0, 10), valign=:bottom)

    scene
end
```

<img width="370" alt="grafik" src="https://user-images.githubusercontent.com/22495855/71010977-f3084e80-20ec-11ea-9ffe-5f3c800a38f8.png">

This requires manual adjustment of the padding if you need to make room for xticklabels etc.
