### ISSUE TITLE
Mouse picking transformation

### ISSUE THREAD

**Issue by vilim** [jkrumbiegel/MakieLayout#21]
I am trying to make an interactive interface with MakieLayout, which involves picking on the canvas (at some point I would also like to implement a [toyplot-like theme](https://toyplot.readthedocs.io/en/stable/tutorial.html)). However I am struggling to find the appropriate methods and properties for the mouse-to-data coordinates transformation.

```julia
scene, layout = layoutscene(30, resolution = (600, 600))
ax = (layout[1,1] = LAxis(scene))
hmp = heatmap!(ax, rand(100,100));
mouse_st = MakieLayout.addmousestate!(scene, hmp)

# make a node list of points for the crosshairs
draw_lines = lift(mouse_st) do mst
   if mst.typ == MakieLayout.MouseOver()
       x, y = to_world(hmp.parent, mst.pos)
       p = [Point2f0(x, 0),
            Point2f0(x, 100),
            Point2f0(0, y),
            Point2f0(100, y)]
    else
       p = [Point2f0(0,0)] 
    end
    p
end

lsgs = linesegments!(ax, draw_lines, color="red", linewidth=3) # is there a function for infinite horizontal/vertical lines?
display(scene)
```

This is the closest I have gotten, but there is still a mysterious offset between the mouse and crosshairs coordinates.

**Comment by jkrumbiegel** [comment]
Hi, you're basically trying to calculate pixel positions and then plot pixels in the data coordinates of your plot. That can not work. The fact that it looks like it's almost working is actually pointing to some buggy behavior that I need to fix (the position is somehow given in data coordinates, not in pixels). Here's a working version:

```julia
using Makie
using MakieLayout


# coordinate transformation between two rects
function transferrects(pos, rectfrom, rectto)
   fracpos = (pos .- rectfrom.origin) ./ rectfrom.widths
   fracpos .* rectto.widths .+ rectto.origin
end


begin
   scene, layout = layoutscene(30, resolution = (600, 600))
   ax = (layout[1,1] = LAxis(scene))
   hmp = heatmap!(ax, rand(100,100));
   

   # make a node list of points for the crosshairs
   draw_lines = lift(events(ax.scene).mouseposition) do pos
      x, y = transferrects(pos, ax.scene.px_area[], ax.limits[])

      x1, y1 = ax.limits[].origin
      x2, y2 = ax.limits[].origin + ax.limits[].widths
       
      p = if AbstractPlotting.is_mouseinside(ax.scene)
         [Point2f0(x, y1),
         Point2f0(x, y2),
         Point2f0(x1, y),
         Point2f0(x2, y)]
      else
         [Point2f0(0,0)] 
      end
      p
   end

   lsgs = linesegments!(ax, draw_lines, color="red", linewidth=3) # is there a function for infinite horizontal/vertical lines?
   display(scene)
end
```

A couple notes:

If you use the mouseover event of the heatmap and then place a line under the mouse, the line will block the mouse from being "over" the heatmap, because in GLMakie picking is determined using pixel values. So if you want a mouseover event over the whole space, you can just use the scene. And if you don't need any other mouse events, you can just use the standard mouse position event and `is_mouseinside`. (`addmousestate` should also work with the complete scene).

I haven't exported any functions for limit-dependent plots yet, because there's no clean way yet to exclude them from auto limit calculation (they would just constantly cause the auto limits to expand until they're at infinity). But you can see a relatively recent example in this gist https://gist.github.com/jkrumbiegel/bd98cf311f94b589272ad8c0e0ca60b3 with these functions:

```julia
function axhline!(la::LAxis, y::Node; kwargs...)
    points = lift(la.limits, y) do lims, y
        x1 = lims.origin[1]
        x2 = lims.origin[1] + lims.widths[1]
        Point2f0.([(x1, y), (x2, y)])
    end

    lines!(la, points; xautolimit=false, kwargs...)
end

function axvline!(la::LAxis, x::Node; kwargs...)
    points = lift(la.limits, x) do lims, x
        y1 = lims.origin[2]
        y2 = lims.origin[2] + lims.widths[2]
        Point2f0.([(x, y1), (x, y2)])
    end

    lines!(la, points; yautolimit=false, kwargs...)
end
```

As you can see, it's pretty straightforward to define such functions yourself right now if you need them, until they're officially exported at some point.

**Comment by vilim** [comment]
Thank you, this is very clear and comprehensive!
