### ISSUE TITLE
align legend

### ISSUE THREAD

**Issue by edljk** [jkrumbiegel/MakieLayout#27]
What would be the easiest way to modify the  [first example of the documentation](https://jkrumbiegel.github.io/MakieLayout.jl/dev/index.html) to align the height of the legend box with the top and bottom edges of the axis boxes?

**Comment by jkrumbiegel** [comment]
You want the legend box to have the same height as the axis? The legend height depends on its content, so it will just be the size that it needs to be. You can change the height by changing the element sizes and the number of columns, the rest will be automatic. If it was possible to fix the height to the axis height, the content would simply not fit in most cases. What you can do instead is have the axis height correspond to the legend height, by setting the legend's height to `Auto(true)` instead of `Auto(false)`. This will make the GridLayout row shrink to the legend, taking the axis with it.

**Comment by edljk** [comment]
Perfect, thanks!
