### ISSUE TITLE
How to change position of slider.

### ISSUE THREAD

**Issue by aramirezreyes** [jkrumbiegel/MakieLayout#34]
Hi!

I have a slider created by:
```
Using AbstractPlotting, GLMakie, MakieLayout
scene, layout = layoutscene()
sl = LSlider(scene, range=1:10)
```
If I move the slider with my mouse, to the middle, I can retrieve the value by:
```
sl.value[]
```
However, if I modify thi:
```
sl.value[] = 1
```
The position of the silder does not vary accordingly.

How can I make this happen?

My first thought was to implement an action similar to:
```
    on(attrs.value) do i
        #update displayed_sliderfraction[]
    end
```

at https://github.com/jkrumbiegel/MakieLayout.jl/blob/ffc8e4efb94044a37db38ca171a78528dc1a982f/src/lobjects/lslider.jl#L72

However, changing sl.value from the outside doesn't seem to trigger this action. 
Is there an easy way to solve this?

**Comment by aramirezreyes** [comment]
I created this pull request, which is work in progress https://github.com/jkrumbiegel/MakieLayout.jl/pull/35

**Comment by jkrumbiegel** [comment]
Hm this circular updating is always a bit tricky, complicated in this case by the fact that a slider has a range of values that are possible, and theoretically you could set the `value` observable to something else that isn't possible to display. That's why I don't think it works well to change the value observable directly (thereby maybe triggering unwanted consequences for an illegal value). I've just added a function `set_close_to!(slider, value)` that should do what you want and tagged a new version.

**Comment by aramirezreyes** [comment]
This is great!, Thanks!
