### ISSUE TITLE
Updating slider.value does not actually update the slider visuals

### ISSUE THREAD

**Issue by Datseris** [jkrumbiegel/MakieLayout#65]
For interactive applications where `reset` buttons are used, some sliders need to be changed to some values programmatically.

After initializing a slider, doing `slider.value[] = other_val` does update the slider's value, but not the visuals. Visually the slider is stuck at the same position.

**Comment by jkrumbiegel** [comment]
ah that's because a slider's range is really a range with a finite set of values, so you can't set it to just any value, it has to be one of those. so it actually has to internally be set to the integer index of a certain value. There's a function for this, `set_close_to!(slider, value)`, because exact placement is only possible for values that are in the range

**Comment by jkrumbiegel** [comment]
that's why you can't just set value[] to what you want sadly

**Comment by Datseris** [comment]
Hm, adding the simple:
```
on(slider.value) do val; set_close_to!(slider, val); end
```
produces `StackOverflow`. Could you please be more specific about this?

When I press a button I update  `slider.value`, so I naively thought that the above would do what I want.

---

So the only way I guess is to explicitly do `set_close_to!(slider, value)` for each button I [press and for each slider I have.

**Comment by Datseris** [comment]
By the way, I haven't said it, but I do put the slider to its exact value, i.e. I try to put a slider in a value that guaranteed exists in the slider's `range`. So for some reason I think that this should happen internally, that the slider visuals are updated, instead of externally by the user. Somehow the order that `set_close_to!` is used must be changed, so that it can also work the other way. At the moment only one way works: moving the slider. But the other way, setting the slider observable programmatically, should also work and update the visuals.

EDIT: Okay, I now understand that this might not be entirely possible, because `slider.value` is just a normal observable.

**Comment by Datseris** [comment]
Okay, I've solved my issue by adding one more `on` call, like so:
```
    onany(▢reset, ▢back) do val1, val2
        j, p₋, p₊, xmin, xmax, m, T, dens = history[end]
        set_close_to!(nslider, m)
        set_close_to!(Tslider, T)
        set_close_to!(dslider, dens)
    end
```
Should I close this?

**Comment by jkrumbiegel** [comment]
Above you just created a circle, on any slider value change change the slider value ;) You can't set `value` because that's an output of the slider, not the input. The position of the slider can't depend on the output as that would be circular. So `value` doesn't determine the slider position, rather both value and slider position are controlled by an internal observable that tracks the index of the selected range value. And you can only set that to integer values obviously, which the function set_close_to does for you

**Comment by jkrumbiegel** [comment]
So you did it correctly in the later examples. But there is also an observable `start_value` and you can reset the slider to that by double clicking it. Maybe there's also `reset!` function to go with that, don't remember and I'm on my phone
